Sprint 1
AntLer-24rus/middle.messenger.praktikum.yandex pull request #1
Opened 2022-04-21 16:47 UTC by AntLer-24rus

Ссылка на шаблоны [figma](https://www.figma.com/file/sySPP1pk1sEVnBZWNWClME/AntLer-Chat?node-id=0%3A1)
Ссылка на [netlify](https://ubiquitous-entremet-7f80bf.netlify.app)

2022-04-21 20:44 UTC, ua9msn requested changes

2022-04-21 20:44 UTC, ua9msn commented on src/modules/button/style.module.scss
> +    border: 1px solid #409eff;
Цвета можно вынести в переменные, тем более вы уже импортируете variables

2022-04-21 20:44 UTC, ua9msn commented on src/modules/dev-panel/dev-panel.hbs
> +      <li><a href='/{{this}}' onclick='linkHandler(event)'>{{this}}</a></li>
this обычно используется иначе. Вы уверены что это строка?

2022-04-21 20:44 UTC, ua9msn commented on src/modules/dev-panel/style.module.scss
> +  background: #455868;
Цвета обычно выносятся в переменные

2022-04-21 20:44 UTC, ua9msn commented on src/modules/index.js
> +export default new Map([
`export default` был придуман для совместимости с `commonjs` Нет никакое нужды использовать его в новых проектах, лучше использовать именованый экспорт

2022-04-21 20:44 UTC, ua9msn commented on src/modules/input/style.module.scss
> +    color: #ff0000;
Все то же про цвета и переменные

2022-04-21 20:44 UTC, ua9msn commented on src/pages/error/style.module.scss
> +    padding-top: calc(169px - 20px) !important;
Какой смысл в `calc` от константных значений? 
`!important` - признак плохой архитектуры. Его используют крайне редко для переопределения стилей старых библиотек

2022-04-21 20:44 UTC, ua9msn commented on src/style.scss
> +  background: linear-gradient(296.82deg, #ebf4f5 0%, #b5c6e0 100%);
ВСЕГДА проверяйте значения из сторонних инструментов, например онлайн генераторов. Дробный угол, зачем?

2022-04-21 20:44 UTC, ua9msn commented on src/utils/mountPage.js
> +        text: 'Меняем электро проигрыватель на электро выигрыватель',
Годвиль? (Если не знаете про годвиль, не обращайте внимания)

2022-04-23 03:50 UTC, AntLer-24rus commented on src/utils/mountPage.js
> +        text: 'Меняем электро проигрыватель на электро выигрыватель',
Не знаю, пытался гуглить - понятней не стало =(

2022-04-24 07:56 UTC, ua9msn approved these changes

2022-04-28 02:29 UTC, merged